In [2]:
import numpy as np

In [75]:
#array 1 dimensi
array_1 =np.array([1,2,3,5])
array_1

array([1, 2, 3, 5])

In [76]:
#array 2 dimensi
array_2 = np.array([[1,2,5],[3,6,8]])
array_2

array([[1, 2, 5],
       [3, 6, 8]])

In [77]:
#array dengan fungsi bawaan
zero = np.zeros([2,3]) # 2 baris 3 kolom
zero


array([[0., 0., 0.],
       [0., 0., 0.]])

In [78]:
#array 1 
satu = np.ones([2,2])
satu

array([[1., 1.],
       [1., 1.]])

In [17]:
#array dengan rentang angka
arange_c = np.arange(0,10,2)
arange_c

array([0, 2, 4, 6, 8])

In [30]:
#array dengan nilai random
arandom = np.random.rand(3,2) # array 3x2 dengan nilai acak
arandom

array([[0.81478248, 0.18547494],
       [0.90493233, 0.80471199],
       [0.93965904, 0.52842159]])

In [79]:
#manipulasi array
 
print(array_2[0]) # akses elemen pertama
print(array_2[0,1])  # akses elemen pada baris ke-1 dan kolom ke-2

[1 2 5]
2


In [81]:
#slicing
print(array_2[1:4]) # ambil elemen dari index 1 sampai 3

[[3 6 8]]


In [83]:
#mengubah bentuk array
reshapee = array_2.reshape(3,2)
reshapee

array([[1, 2],
       [5, 3],
       [6, 8]])

In [84]:
# menggabungkan 
array1a = np.array([1, 2, 3])
array2a = np.array([4, 5, 6])
combined = np.concatenate((array1a, array2a))
print(combined)


[1 2 3 4 5 6]


In [85]:
split_array = np.split(combined, 3)
print(split_array)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [86]:
#operasi matematika
array_aa = np.array([1, 2, 3])
array_bb = np.array([4, 5, 6])

print(array_a + array_b)  # penjumlahan
print(array_a * array_b)  # perkalian


[5 7 9]
[ 4 10 18]


In [87]:
#statistik
print(np.mean(array_a))  # rata-rata
print(np.median(array_a))  # median
print(np.std(array_a))  # standar deviasi


2.0
2.0
0.816496580927726


In [90]:
import numpy as np

# Membuat array 2D
array_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Mengakses elemen tertentu
print("Elemen baris 1 kolom 2:", array_2d[0, 1])  # Output: 20
print("Elemen baris 3 kolom 1:", array_2d[2, 0])  # Output: 70

# Mengambil seluruh baris
print("Seluruh baris 2:", array_2d[1, :])  # Output: [40, 50, 60]

# Mengambil seluruh kolom
print("Seluruh kolom 3:", array_2d[:, 2])  # Output: [30, 60, 90]

# Mengambil sub-array
print("Sub-array (2x2):")
print(array_2d[0:2, 0:2])  # Output: [[10, 20], [40, 50]]


Elemen baris 1 kolom 2: 20
Elemen baris 3 kolom 1: 70
Seluruh baris 2: [40 50 60]
Seluruh kolom 3: [30 60 90]
Sub-array (2x2):
[[10 20]
 [40 50]]
