In [4]:
import numpy as np
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
total_sum = np.sum(array_2d)
print(total_sum)  # Output: 45


45


In [ ]:
mean_value = np.mean(array_2d)
print(mean_value)  # Output: 5.0

In [6]:
median_value = np.median(array_2d)
print(median_value)  # Output: 5.0

5.0


In [7]:
std_dev = np.std(array_2d)
print(std_dev)  # Output: 2.581988897471611

2.581988897471611


In [8]:
#axis=0 untuk melakukan operasi pada kolom.
#axis=1 untuk melakukan operasi pada baris.

sum_by_column = np.sum(array_2d, axis=0)
print(sum_by_column)  # Output: [12 15 18]

#Kolom 0: 1 + 4 + 7 = 12
#Kolom 1: 2 + 5 + 8 = 15
#Kolom 2: 3 + 6 + 9 = 18

[12 15 18]


In [9]:
sum_by_baris = np.sum(array_2d, axis=1)
print(sum_by_baris)


[ 6 15 24]
